### ISSUE TITLE
0.1.8 could not find

### ISSUE THREAD

**Issue by xiaomage1478** [hilen/TSVoiceConverter#15]
pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "TSVoiceConverter":
  In Podfile:
    TSVoiceConverter (= 0.1.8)

None of your spec sources contain a spec satisfying the dependency: `TSVoiceConverter (= 0.1.8)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by lanceylai** [comment]
done
