### ISSUE TITLE
Swift 2.3 version not available in cocoapods

### ISSUE THREAD

**Issue by mime29** [hilen/TSVoiceConverter#2]
I tried to pod install today and I got a version 0.1.2 with Swift 3.
That s a problem because old projects won t compile anymore.
Could you restore the 0.1.2 version on cocopods and make the Swift 3 version the version 0.1.3 for example?

**Comment by lanceylai** [comment]
I will fix it and make it to version 0.1.3.

**Comment by lanceylai** [comment]
I've been released 0.1.3 and support Swift 3.0. Have a try?
