### ISSUE TITLE
Failed to convert amr to wav

### ISSUE THREAD

**Issue by NicholasFLee** [hilen/TSVoiceConverter#7]
Hello there, I have a .amr file downloaded from server, and it failed to convert to wav by TSVoiceConverter. 
the file is: http://img.nikkitoday.com/test/v2/resource/public?rid=5a26576047e6260007b8b8ca

**Comment by NicholasFLee** [comment]
solved because Android side problem.

**Comment by lanceylai** [comment]
I tried to debug the file, and it showed amr header string is empty. 
![image](https://user-images.githubusercontent.com/2245840/33599269-9a7e07b4-d9e0-11e7-8e9a-93443d6e35ce.png)

And the hello.amr file in the project showed `magic:#!AMR`. So you can check the file's info.

**Comment by NicholasFLee** [comment]
@hilen Lesson learned, thanks for your time to debug it :)
